[package]
name = "execution"
description = "Execution exercises"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { workspace = true, features = ["std"] }

frame-system = { workspace = true, features = ["std"] }
frame-support = { workspace = true, features = ["std"] }
pallet-message-queue = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std"] }

emulator = { path = "../emulator" }

xcm = { workspace = true, features = ["std"] }
xcm-runtime-apis = { workspace = true, features = ["std"] }

[dev-dependencies]
env_logger = { workspace = true }
test-log = { workspace = true }
