[package]
name = "emulator"
description = "XCM Emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
codec = { workspace = true, features = ["std"] }
scale-info = { workspace = true, features = ["std"] }
log = { workspace = true, features = ["std"] }

# Local
parachain-runtime = { package = "parachain", path = "../parachain" }

frame-system = { workspace = true, features = ["std"] }
frame-support = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["std"] }
pallet-assets = { workspace = true, features = ["std"] }
pallet-message-queue = { workspace = true, features = ["std"] }
pallet-uniques = { workspace = true, features = ["std"] }
pallet-staking = { workspace = true, features = ["std"] }
parachain-info = { workspace = true, features = ["std"] }

sp-std = { workspace = true, features = ["std"] }
sp-core = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std"] }
sp-weights = { workspace = true, features = ["std"] }
sp-tracing = { workspace = true, features = ["std"] }
sp-authority-discovery = { workspace = true, features = ["std"] }
sp-consensus-babe = { workspace = true, features = ["std"] }
sp-consensus-beefy = { workspace = true, features = ["std"] }
sp-keyring = { workspace = true, features = ["std"] }
sc-consensus-grandpa = { workspace = true }

polkadot-core-primitives = { workspace = true, features = ["std"] }
polkadot-runtime-parachains = { workspace = true, features = ["std"] }
polkadot-parachain-primitives = { workspace = true, features = ["std"] }
polkadot-primitives = { workspace = true, features = ["std"] }
parachains-common = { workspace = true, features = ["std"] }
cumulus-primitives-core = { workspace = true, features = ["std"] }
emulated-integration-tests-common = { workspace = true }
westend-runtime = { workspace = true }
westend-runtime-constants = { workspace = true }
asset-hub-westend-runtime = { workspace = true }

xcm = { workspace = true, features = ["std"] }
xcm-executor = { workspace = true, features = ["std"] }
xcm-builder = { workspace = true, features = ["std"] }
xcm-emulator = { workspace = true }
pallet-xcm = { workspace = true, features = ["std"] }

deranged = { workspace = true }
